### ISSUE TITLE
[feat] react-query를 이용한 서버 통신

### ISSUE THREAD

**Issue by greenish0902** [wanted-group-4/ad-platform#33]
## ISSUE
- Group: `server`
- Type: `fix`
- Detail: fix api

## TODO
- [x] 대시보드 페이지 api 변경: 기존에 recoil을 이용한 fetching 에서 react-query 이용하도록 변경
- [x] 광고관리 페이지 update 구현
- [x] 서버 CRUD 이후 클라이언트 데이터도 리렌더링되도록 구현

## Labels
Estimated time: E: `3h`
Group : `server`
