### ISSUE TITLE
[refactor] Line chart 리팩토링 

### ISSUE THREAD

**Issue by JiehoonPark** [wanted-group-4/ad-platform#39]
## ISSUE
- Group: `client`
- Type: `refactor`
- Detail: Line chart 컴포넌트 리팩토링

## TODO
- [x] board page 와 연결 
- [ ] 최대한 클린코드 
- [ ] 코드중복 검사후 최소화
- [ ] select 리스트 데이터에 따라 동적으로 보낼수있도록 바꿔보기

## Labels
Group : `client`
