### ISSUE TITLE
[feat] Board 페이지 test code 작성

### ISSUE THREAD

**Issue by greenish0902** [wanted-group-4/ad-platform#40]
## ISSUE
- Group: `server`
- Type: `feature`
- Detail: feat api test code - Board 페이지 test code 작성해서 데이터 연동 여부 확인

## TODO
- [x] react-query 로 api 연동
- [x] api로 받은 데이터 페이지에 전달
- [x] Board 페이지 내부의 axios 연동 외부로 추출

## Labels
Estimated time: E: `3h`
Group : `server`
