### ISSUE TITLE
[feat] 상태관리

### ISSUE THREAD

**Issue by greenish0902** [wanted-group-4/ad-platform#8]
## ISSUE
- Group: `client`
- Type: `feature`

## TODO
- [x] 상태관리 라이브러리 서치
- [x] 사용하는 목적과 이유를 정의하고
- [x] 해당 목적에 맞는 라이브러리 사용하기

## Labels
Estimated time: E: `3h`
Group : `client`
